import React from 'react';

interface FooterProps {
  onAdminClick: () => void;
}

const Footer: React.FC<FooterProps> = ({ onAdminClick }) => {
  return (
    <footer className="bg-gray-900 text-gray-400 py-6 mt-12">
      <div className="container mx-auto text-center px-4">
        <p>&copy; {new Date().getFullYear()} Gemini MovieStream. All rights reserved.</p>
        <p className="text-sm mt-1">Movie data generated by Google Gemini.</p>
        <button 
          onClick={onAdminClick}
          className="text-xs text-gray-500 hover:text-red-400 mt-4 transition-colors"
          aria-label="Open Admin Panel"
        >
          Admin Panel
        </button>
      </div>
    </footer>
  );
};

export default Footer;
